version: "3.2"

services:
  nginx: 
    image: reverseproxy
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - autenticacao
      - servidoremail
    networks: 
      - redeNginxAuth
      - redeNginxEmail

  servidoremail:
    image: vr/compositor #jorgeoliv/vr2_servicoemail
    restart: always
    container_name: servidoremail
    ports:
      - "4000:4000"
    #entrypoint: ["npm", "start"]
    networks: 
      - redeAuthComp
      - redeCompServEmail
      - redeNginxEmail

  autenticacao:
    image: vr/auth #jorgeoliv/vr2_autenticacao
    restart: always
    container_name: autenticacao
    ports:
      - "3000:3000"
    #entrypoint: ["npm", "start"]  
    depends_on:
      - mongodb
    networks: 
      - redeAuthBD
      - redeAuthComp
      - redeNginxAuth

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - type: volume
        source: mongoVolume
        target: /data/db #/var/lib/mongodb/data
      # - type: bind
      #   source: ./data/db
      #   target: /data/db
    ports:
        - 27018:27017
    command: mongod --noauth --smallfiles
    networks:
        - redeAuthBD
  
  maildev:
    image: djfarrelly/maildev
    restart: always
    container_name: maildev
    ports:
        - 1080:80
    networks:
        - redeCompServEmail
            
networks:
    redeAuthBD:
        driver: bridge
    redeAuthComp:
        driver: bridge
    redeCompServEmail:
        driver: bridge
    redeNginxAuth:
      driver: bridge
    redeNginxEmail:
      driver: bridge

volumes:
  mongoVolume:
    driver: local
#     #dst: /data/db