version: "2"

services:
  compositor:
    image: vr/compositor
    restart: always
    container_name: servidoremail
    ports:
      - "4000:4000"
    depends_on:
      - mail
    #entrypoint: ["npm", "start"]
    networks: 
      - redeAuthComp
      - redeCompServEmail

  auth:
    image: vr/auth
    restart: always
    container_name: autenticacao
    ports:
      - "3000:3000"
    #entrypoint: ["npm", "start"]  
    depends_on:
      - mongodb
    networks: 
      - redeAuthBD
      - redeAuthComp

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
        - ./data-node:/data/db
    ports:
        - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
        - redeAuthBD
  
  mail:
    image: djfarrelly/maildev
    restart: always
    container_name: maildev
    ports:
        - 1080:80
    networks:
        - redeCompServEmail
            
networks:
    redeAuthBD:
        driver: bridge
    redeAuthComp:
        driver: bridge
    redeCompServEmail:
        driver: bridge