version: "3.2"

services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./stylesheets/style.css:/etc/nginx/html/stylesheets/style.css
    depends_on:
      - autenticacao
      - servidoremail
    networks: 
      - redeNginxAuth
      - redeNginxEmail

  servidoremail:
    image: vr/compositor #jorgeoliv/vr2_servicoemail
    restart: always
    container_name: servidoremail
    ports:
      - "4000:4000"
    depends_on:
      - historicdb
    #entrypoint: ["npm", "start"]
    networks: 
      - redeAuthComp
      - redeCompServEmail
      - redeNginxEmail
      - redeCompHist

  autenticacao:
    image: vr/auth #jorgeoliv/vr2_autenticacao
    restart: always
    container_name: autenticacao
    # volumes:
    #   - type: volume
    #     source: ./mydata
    #     target: mongoVolume
    #     volume:
    #       nocopy: true
    ports:
      - "3000:3000"
    #entrypoint: ["npm", "start"]  
    depends_on:
      - mongodb
    networks: 
      - redeAuthBD
      - redeAuthComp
      - redeNginxAuth

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      # # - type: volume
      # #   source: mongoVolume
      # #   target: /data/db #/var/lib/mongodb/data
      # - type: bind
      #   source: mongoVolume
      #   target: /data/db
      - mongoVolume:/data/db
    ports:
        - 27018:27017
    command: mongod --noauth --smallfiles
    networks:
        - redeAuthBD

  historicdb:
    image: mongo
    restart: always
    container_name: historicdb
    volumes:
      # # - type: volume
      # #   source: mongoVolume
      # #   target: /data/db #/var/lib/mongodb/data
      # - type: bind
      #   source: mongoVolume
      #   target: /data/db
      - historicVolume:/data/db
    ports:
        - 27019:27017
    command: mongod --noauth --smallfiles
    networks:
        - redeCompHist
  
  maildev:
    image: djfarrelly/maildev
    restart: always
    container_name: maildev
    ports:
        - 25:25
    networks:
        - redeCompServEmail
            
networks:
    redeAuthBD:
        driver: bridge
    redeAuthComp:
        driver: bridge
    redeCompServEmail:
        driver: bridge
    redeNginxAuth:
      driver: bridge
    redeNginxEmail:
      driver: bridge
    redeCompHist:
      driver: bridge

volumes:
  mongoVolume:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/Desktop/data_mongo/
      o: bind
  historicVolume:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/Desktop/data_historic/
      o: bind
#   mydata:
# #     #dst: /data/db